name: variable example

on:
   push:
        branches: [main]

jobs: 
    greeting_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
        steps:
            -name: display my name
            run: echo "my name is $first_name"
            env:
                first_name: "shraavya"
